name: Upload Resume (development)

on:
  push:
    branches:
      - development

permissions:
  id-token: write

jobs:
  write-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEV_DEPLOY_ROLE }}
          role-session-name: OIDCSession

      - run: aws s3 sync ./public/ s3://dev.resume.chucknemeth.com --delete
        shell: bash
